### ISSUE TITLE
Add MP Comment Functionality

### ISSUE THREAD

**Issue by Jhernandez29** [US-EPA-CAMD/PI-1#6791]
Continuation of #6740 

Add/Edit Monitoring Plan Comments screen from ECMPS 1.0:
![Image](https://github.com/user-attachments/assets/2aa53293-4664-4c6b-b687-e86b69831ba2)

## Requirements
 
- For adding a new comment record, there should be three fields: Monitoring Plan Comment, Begin Date, and End Date
     - Monitoring Plan Comment and Begin Date fields are required when saving a new record.
          - If the Monitoring Plan Comment field is null, a MONPLAN-7-A screen check error should fire.
          - If the Begin Date field is null, a MONPLAN-4-A screen check error should fire
          - If the End Date is before the Begin Date, a MONPLAN-6-A screen check error should fire
- When a user saves a new MP comment, a record should be added in the CAMDECMPSWKS.MONITOR_PLAN_COMMENT table
     -  If a user saves a new comment record, the Monitoring Plan should be marked as resubmission required and will need to be evaluated.
- Users should be able to Edit MP comment records in the UI. Users can edit the Monitoring Plan Comment, Begin Date, and End Date fields
- Users should be able to remove Monitoring Plan Comments from the workspace that have not been submitted to official yet. 
- When a user submits a Monitoring Plan with a new/ edited comment, the comment should be loaded to the CAMDECMPS.MONITOR_PLAN_COMMENT table.
     - If a user tries to remove a MP comment that has already been submitted to official, an error message should fire. Error message from ECMPS 1.0 included below:
          - ![Image](https://github.com/user-attachments/assets/b4543c58-9968-4b73-877e-23d97010235d)
- If a user imports a MP JSON with new comment records, the comments should appear in the UI.

## Acceptance Criteria

- Able to add new MP comment records in the UI and submit. After submission, revert to official and verify that comment is still present.
     - Verify that Monitoring Plan Comment and Begin Date fields are required to save a comment record.
- Able to edit MP comment records in the UI, save changes, and submit. After submission, revert to official and verify that edits to comment are still present.
     - Should be able to edit the Monitoring Plan Comment, Begin Date, and End Date fields.
- Able to import an MP JSON with new MP comment and view/ edit the comment in the UI
- Should be able to remove Monitor Plan Comments from the workspace that have not been submitted to official yet. 
- If a user tries to remove a MP comment that has already been submitted to official, and is also present in the workspace the comment should not be remove from official. 
- Able to evaluate changes in UI 
- Able to submit changes to official record in submission UI.

**Comment by Jhernandez29** [comment]
1. **Users should be able to remove Monitoring Plan Comments from the workspace that have not been submitted to official yet.** 
 This is done with   @Delete(':planId/revert')  

Revert workspace monitor plan back to official submitted record'   

2. **In ECMPS 2.0 If a user tries to remove a MP comment that has already been submitted to official, an error message does not fire like Error message from ECMPS 1.0 included below:**
 ![Image](https://github.com/user-attachments/assets/f1817719-5caf-40e0-9c6d-eed3444b899e)

**It just doesn't revert/delete workspace record because record also lives in official table.** 
Sets MONITOR_PLAN.UPDATED_STATUS_FLG to 'Y'.
Sets MONITOR_PlAN.LAST_UPDATED to current timestamp.

**Comment by mxtomoto1** [comment]
Testing was done using a multi-role account, DP account, and DS account.  
 
- Able to add new MP comment records in the UI and submit. After submission, revert to official shows that comment is still present.
   - Verified that Monitoring Plan Comment and Begin Date fields are required to save a comment record; screen checks MONPLAN-7-A, MONPLAN-4-A, and MONPLAN-6-A are present.
- Able to edit MP comment records in the UI, save changes, and submit. After submission, revert to official shows that edits to submitted comment are still present.
   - Able to edit the Monitoring Plan Comment, Begin Date, and End Date fields.
- Able to import an MP JSON with new MP comment and view/ edit the comment in the UI
- Able to remove Monitor Plan Comments from the workspace that have not been submitted to official yet by reverting to official before submitting.
   - **Bug / Enhancement**: On Microsoft Edge (with DP only account), reverting to delete a comment causes the comment to still be visible in the UI until the page refreshes. The UI prevents edits to the deleted (but visible) comment by an error. New ticket: #6880 
- If a user tries to remove a MP comment that has already been submitted to official, and is also present in the workspace the comment will not be removed from official. Importing a MP without the submitted comment does not remove the submitted comment from the workspace, and re-exporting the resulting MP will have the submitted comment in the resulting MP.
- Able to evaluate changes in UI
   - **Bug**: When a user has a comment in the workspace, has the MP on the Evaluate screen, and goes to navigate off the Evaluate screen without evaluating the MP, the UI will give an error screen before going to the desired screen.
- Able to submit changes to official record in submission UI. New ticket: #6881

**Comment by alangmaid** [comment]
@mxtomoto1 add your QA results from #6881 to this ticket and then delete #6881. Do the same with #6880

**Comment by mxtomoto1** [comment]
## Bug/Enhancement: deleted MP comments still visible on Edge (formerly ticket #6880 )

On Microsoft Edge (observed with DP only account), reverting to official to delete a comment sometimes causes the comment to still be viewable in the UI until the page refreshes. This has been observed on the latest version of Edge (Version 139.0.3405.86 (Official build) (64-bit) as of 8/11/2025) and seems to occur less frequently on the first attempt at creating a new comment on an instance of the browser.

The Evaluation Status of the MP will be the correct status. The UI prevents edits to the deleted (but visible) comment by an error (screenshot with dev tools):

<img width="1919" height="1027" alt="Image" src="https://github.com/user-attachments/assets/178926b7-abc4-448b-981c-dcddc3418855" />

[ecmps-dev.app.cloud.gov-1754929435255.log](https://github.com/user-attachments/files/21720527/ecmps-dev.app.cloud.gov-1754929435255.log)
[ecmps-dev.app.cloud.gov-1754929408048.log](https://github.com/user-attachments/files/21720526/ecmps-dev.app.cloud.gov-1754929408048.log)

<img width="1919" height="1025" alt="Image" src="https://github.com/user-attachments/assets/0753d3d2-b927-4a76-9ee0-11095e223609" />

### Steps to recreate

1. Create a new MP comment using Edge browser.
2. Delete comment by Revert to Official.
3. Observe that the comment is still viewable on page.
4. Refresh (and reopen the configuration from the resulting configuration select screen) to observe that the comment no longer remains.

## Bug: Having a comment in the workspace to be evaluated causes navigation error screen (formerly ticket #6881 )

When a user has a new or edited comment in the workspace, has the MP on the Evaluate screen, and goes to navigate off the Evaluate screen without evaluating the MP, the UI will give an error screen (screenshot) before going to the desired screen.

<img width="1477" height="890" alt="Image" src="https://github.com/user-attachments/assets/b5983246-e23e-4829-958e-cbefca8239ff" />

### Steps to recreate:

1. Create a new MP comment or edit an existing one.
2. Load that MP into the Evaluate workspace, but do not evaluate.
3. Navigate off the Evaluate module to another module.

**Comment by Jhernandez29** [comment]
@mxtomoto1  Added PR to fix bug regarding navigation error screen in evaluation. https://github.com/US-EPA-CAMD/easey-ecmps-ui/pull/1683

**Comment by Jhernandez29** [comment]
@mxtomoto1  Added PR to fix Bug/Enhancement: deleted MP comments still visible on Edge (formerly ticket https://github.com/US-EPA-CAMD/easey-ui/issues/6880 ). It actually wasn't an edge issue. It was a bug in the DataTableComments component. The Reverted state wasn't updated properly.

**Comment by mxtomoto1** [comment]
Testing was done using a multi-role account and DP account. All testing in the above comment (https://github.com/US-EPA-CAMD/easey-ui/issues/6791#issuecomment-3168890356) is still valid.

The aforementioned issues (deleted comments remaining viewable and the evaluate navigation error) were unable to be recreated; the issues appear resolved.

A new issue has been observed that appears only on Comanche (470) location 1 where attempting to import MP results in a null ID error.

<img width="1908" height="984" alt="Image" src="https://github.com/user-attachments/assets/3858b60d-864b-421d-b90e-16366d57ca49" />

**Comment by mxtomoto1** [comment]
Testing was done using a multi-role account and DP account. All testing in the above comment (https://github.com/US-EPA-CAMD/easey-ui/issues/6791#issuecomment-3168890356) is still valid.

The aforementioned issues (deleted comments remaining viewable and the evaluate navigation error) were unable to be recreated; the issues appear resolved.

The Comanche 1 import issue has been resolved. 

However, currently when attempting to import a MP with a comment that has a begin date that cannot be mapped to MP dates on file (ex. comment begin date after MP end date), the MP will import, but the comment will be omitted. An enhancement could be made to tell the importer if a comment is ignored this way.

**Comment by chrisgitsit** [comment]
Tested comments.  I was able to create comments with different date ranges, submit comments.  I made edits to previously submitted comments but did submitted, original comments were still present after reverting. Are we allowing users to edit previously submitted comments?
